micronaut:
  server:
    port: 8085

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/vulpesdb
    driverClassName: org.postgresql.Driver
    username: vulpes
    password: vulpespassword
    dialect: POSTGRES
    schema-generate: NONE
    maximum-pool-size: 10

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl.auto: update
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
