spring.application.name=Vulpes Backend

spring.data.mongodb.database=vulpes-test
spring.data.mongodb.username=root
spring.data.mongodb.password=example
spring.data.mongodb.authentication-database=admin

logging.level.web=trace