micronaut:
  application:
    name: Vulpes Backend
  server:
    port: ${PORT:8085}
    cors:
      enabled: true
      configurations:
        all:
          allowedOriginsRegex:
            - '^https?://localhost(:\d+)?$'
          allowedMethods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
  logger:
    levels:
      io.micronaut.data: DEBUG
      io.micronaut.sql: DEBUG
      io.micronaut.http.server.cors: TRACE
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**

datasources:
  default:
    url: jdbc:mariadb://localhost:3336/vulpes
    driverClassName: org.mariadb.jdbc.Driver
    username: root
    password: vulpes
    dialect: MYSQL
    schema-generate: CREATE_DROP  # Change to `NONE` or `UPDATE` if you don't want schema recreation
    maximum-pool-size: 10

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl.auto: update  # Use `none` in production
        show_sql: true  # Logs SQL statements
        format_sql: true
